export const tasks: (Record<string, any> & { dueDate: number | Date })[] = [
  {
    id: 1,
    userId: 15,
    title: "Acheter des provisions",
    description: "Lait, Pain, Fromage, Œufs",
    dueDate: 1720176000000,
    status: "pending",
  },
  {
    id: 2,
    userId: 3,
    title: "Terminer le rapport de projet",
    description: "Compléter le rapport final du projet et l'envoyer par email.",
    dueDate: 1720003200000,
    status: "in progress",
  },
  {
    id: 3,
    userId: 18,
    title: "Réserver des billets d'avion",
    description:
      "Réserver des billets d'avion pour New York pour la conférence.",
    dueDate: 1720617600000,
    status: "pending",
  },
  {
    id: 4,
    userId: 8,
    title: "Appeler le plombier",
    description: "Réparer la fuite dans l'évier de la cuisine.",
    dueDate: 1719945600000,
    status: "completed",
  },
  {
    id: 5,
    userId: 14,
    title: "Planifier une réunion",
    description:
      "Organiser une réunion avec le client pour la semaine prochaine.",
    dueDate: 1720089600000,
    status: "pending",
  },
  {
    id: 6,
    userId: 5,
    title: "Préparer la présentation",
    description: "Préparer les diapositives pour la prochaine présentation.",
    dueDate: 1720435200000,
    status: "in progress",
  },
  {
    id: 7,
    userId: 19,
    title: "Faire le ménage",
    description: "Nettoyer la maison avant l'arrivée des invités.",
    dueDate: 1720358400000,
    status: "pending",
  },
  {
    id: 8,
    userId: 10,
    title: "Acheter un cadeau",
    description: "Acheter un cadeau pour l'anniversaire de Marie.",
    dueDate: 1720876800000,
    status: "pending",
  },
  {
    id: 9,
    userId: 13,
    title: "Réviser les documents",
    description: "Réviser les documents pour la réunion de lundi.",
    dueDate: 1720176000000,
    status: "completed",
  },
  {
    id: 10,
    userId: 2,
    title: "Appeler le médecin",
    description: "Prendre rendez-vous chez le médecin pour un bilan de santé.",
    dueDate: 1719945600000,
    status: "pending",
  },
  {
    id: 11,
    userId: 12,
    title: "Envoyer le colis",
    description: "Envoyer le colis à l'adresse de livraison.",
    dueDate: 1720089600000,
    status: "in progress",
  },
  {
    id: 12,
    userId: 6,
    title: "Faire les courses",
    description: "Acheter des fruits et légumes frais pour la semaine.",
    dueDate: 1720176000000,
    status: "completed",
  },
  {
    id: 13,
    userId: 20,
    title: "Écrire un article",
    description: "Écrire un article pour le blog.",
    dueDate: 1720262400000,
    status: "pending",
  },
  {
    id: 14,
    userId: 17,
    title: "Réparer la voiture",
    description:
      "Prendre rendez-vous au garage pour la réparation de la voiture.",
    dueDate: 1720358400000,
    status: "pending",
  },
  {
    id: 15,
    userId: 4,
    title: "Organiser une fête",
    description: "Organiser une fête d'anniversaire pour Julien.",
    dueDate: 1720617600000,
    status: "in progress",
  },
  {
    id: 16,
    userId: 7,
    title: "Rédiger le CV",
    description:
      "Mettre à jour le CV avec les dernières expériences professionnelles.",
    dueDate: 1720435200000,
    status: "completed",
  },
  {
    id: 17,
    userId: 16,
    title: "Réserver un restaurant",
    description:
      "Réserver une table au restaurant pour le dîner de samedi soir.",
    dueDate: 1720358400000,
    status: "pending",
  },
  {
    id: 18,
    userId: 9,
    title: "Acheter des billets de concert",
    description: "Acheter des billets pour le concert de vendredi.",
    dueDate: 1720876800000,
    status: "pending",
  },
  {
    id: 19,
    userId: 11,
    title: "Faire du jogging",
    description: "Faire une séance de jogging matinale.",
    dueDate: 1720089600000,
    status: "completed",
  },
  {
    id: 20,
    userId: 1,
    title: "Réviser pour l'examen",
    description: "Réviser les cours pour l'examen de fin de semaine.",
    dueDate: 1720262400000,
    status: "in progress",
  },
  {
    id: 21,
    userId: 3,
    title: "Nettoyer le garage",
    description: "Ranger et nettoyer le garage.",
    dueDate: 1720176000000,
    status: "pending",
  },
  {
    id: 22,
    userId: 13,
    title: "Aller à la banque",
    description: "Faire un dépôt à la banque.",
    dueDate: 1719945600000,
    status: "completed",
  },
  {
    id: 23,
    userId: 5,
    title: "Réparer le vélo",
    description: "Changer la chaîne du vélo.",
    dueDate: 1720435200000,
    status: "pending",
  },
  {
    id: 24,
    userId: 15,
    title: "Lire un livre",
    description: "Finir de lire le livre commencé.",
    dueDate: 1720617600000,
    status: "in progress",
  },
  {
    id: 25,
    userId: 7,
    title: "Cuisiner un plat",
    description: "Préparer un nouveau plat pour le dîner.",
    dueDate: 1720358400000,
    status: "pending",
  },
  {
    id: 26,
    userId: 8,
    title: "Organiser le bureau",
    description: "Réorganiser le bureau pour plus d'efficacité.",
    dueDate: 1720262400000,
    status: "completed",
  },
  {
    id: 27,
    userId: 2,
    title: "Faire du bénévolat",
    description: "Participer à une activité de bénévolat.",
    dueDate: 1720089600000,
    status: "in progress",
  },
  {
    id: 28,
    userId: 19,
    title: "Jouer au tennis",
    description: "Réserver un court et jouer au tennis.",
    dueDate: 1720176000000,
    status: "pending",
  },
  {
    id: 29,
    userId: 12,
    title: "Prendre des photos",
    description: "Faire une séance photo dans le parc.",
    dueDate: 1720358400000,
    status: "completed",
  },
  {
    id: 30,
    userId: 6,
    title: "Aller au cinéma",
    description: "Voir le dernier film au cinéma.",
    dueDate: 1720435200000,
    status: "pending",
  },
  {
    id: 31,
    userId: 14,
    title: "Apprendre une langue",
    description: "Commencer à apprendre une nouvelle langue.",
    dueDate: 1720262400000,
    status: "in progress",
  },
  {
    id: 32,
    userId: 10,
    title: "Faire du yoga",
    description: "Suivre une séance de yoga en ligne.",
    dueDate: 1720358400000,
    status: "pending",
  },
  {
    id: 33,
    userId: 18,
    title: "Faire des économies",
    description: "Économiser pour les vacances.",
    dueDate: 1720617600000,
    status: "pending",
  },
  {
    id: 34,
    userId: 4,
    title: "Acheter un nouveau téléphone",
    description: "Acheter le dernier modèle de téléphone.",
    dueDate: 1720435200000,
    status: "in progress",
  },
  {
    id: 35,
    userId: 16,
    title: "Aller à la plage",
    description: "Passer une journée à la plage.",
    dueDate: 1720176000000,
    status: "pending",
  },
  {
    id: 36,
    userId: 11,
    title: "Faire du jardinage",
    description: "Planter de nouvelles fleurs dans le jardin.",
    dueDate: 1719945600000,
    status: "completed",
  },
  {
    id: 37,
    userId: 20,
    title: "Peindre une pièce",
    description: "Repeindre le salon.",
    dueDate: 1720089600000,
    status: "pending",
  },
  {
    id: 38,
    userId: 9,
    title: "Visiter un musée",
    description: "Visiter le musée d'art moderne.",
    dueDate: 1720176000000,
    status: "completed",
  },
  {
    id: 39,
    userId: 1,
    title: "Faire une randonnée",
    description: "Faire une randonnée en montagne.",
    dueDate: 1720358400000,
    status: "pending",
  },
  {
    id: 40,
    userId: 17,
    title: "Aller chez le coiffeur",
    description: "Prendre rendez-vous chez le coiffeur.",
    dueDate: 1720435200000,
    status: "in progress",
  },
  {
    id: 41,
    userId: 3,
    title: "Faire du vélo",
    description: "Faire une longue promenade à vélo.",
    dueDate: 1720262400000,
    status: "pending",
  },
  {
    id: 42,
    userId: 13,
    title: "Faire un puzzle",
    description: "Compléter un puzzle de 1000 pièces.",
    dueDate: 1720358400000,
    status: "completed",
  },
  {
    id: 43,
    userId: 5,
    title: "Jouer d'un instrument",
    description: "Apprendre une nouvelle chanson à la guitare.",
    dueDate: 1720435200000,
    status: "pending",
  },
  {
    id: 44,
    userId: 15,
    title: "Méditer",
    description: "Prendre du temps pour la méditation chaque jour.",
    dueDate: 1720617600000,
    status: "in progress",
  },
  {
    id: 45,
    userId: 8,
    title: "Planter un arbre",
    description: "Planter un arbre dans le jardin.",
    dueDate: 1720358400000,
    status: "pending",
  },
  {
    id: 46,
    userId: 18,
    title: "Écrire une lettre",
    description: "Écrire une lettre à un ami.",
    dueDate: 1720262400000,
    status: "completed",
  },
  {
    id: 47,
    userId: 10,
    title: "Faire un don",
    description: "Faire un don à une association caritative.",
    dueDate: 1720089600000,
    status: "in progress",
  },
  {
    id: 48,
    userId: 7,
    title: "Faire des exercices",
    description: "Suivre une routine d'exercices quotidienne.",
    dueDate: 1720176000000,
    status: "pending",
  },
  {
    id: 49,
    userId: 20,
    title: "Regarder un documentaire",
    description: "Regarder un documentaire intéressant.",
    dueDate: 1720358400000,
    status: "completed",
  },
  {
    id: 50,
    userId: 12,
    title: "Préparer un voyage",
    description: "Planifier les détails du prochain voyage.",
    dueDate: 1720435200000,
    status: "pending",
  },
  {
    id: 51,
    userId: 6,
    title: "Faire du tri",
    description: "Trier les vêtements et donner ce qui n'est plus utilisé.",
    dueDate: 1720617600000,
    status: "pending",
  },
  {
    id: 52,
    userId: 14,
    title: "Prendre des cours en ligne",
    description: "S'inscrire à un cours en ligne.",
    dueDate: 1720358400000,
    status: "in progress",
  },
  {
    id: 53,
    userId: 9,
    title: "Dessiner",
    description: "Passer du temps à dessiner chaque jour.",
    dueDate: 1720262400000,
    status: "completed",
  },
  {
    id: 54,
    userId: 4,
    title: "Écouter un podcast",
    description: "Écouter un podcast éducatif.",
    dueDate: 1720089600000,
    status: "pending",
  },
  {
    id: 55,
    userId: 11,
    title: "Faire un pique-nique",
    description: "Organiser un pique-nique dans le parc.",
    dueDate: 1720176000000,
    status: "in progress",
  },
  {
    id: 56,
    userId: 16,
    title: "Essayer une nouvelle recette",
    description: "Cuisiner une nouvelle recette exotique.",
    dueDate: 1720435200000,
    status: "completed",
  },
  {
    id: 57,
    userId: 1,
    title: "Aller au zoo",
    description: "Visiter le zoo avec les enfants.",
    dueDate: 1720262400000,
    status: "pending",
  },
  {
    id: 58,
    userId: 3,
    title: "Faire du camping",
    description: "Organiser un week-end de camping.",
    dueDate: 1720358400000,
    status: "completed",
  },
  {
    id: 59,
    userId: 2,
    title: "Jouer aux échecs",
    description: "Apprendre et jouer aux échecs.",
    dueDate: 1720435200000,
    status: "pending",
  },
  {
    id: 60,
    userId: 17,
    title: "Prendre soin des animaux",
    description: "Aider à la ferme des animaux locaux.",
    dueDate: 1720262400000,
    status: "in progress",
  },
].map((el) => {
  //@ts-expect-error Date OK
  el.dueDate = new Date(el.dueDate);
  return el;
});
